#+TITLE: Nginx Load Balancing Modules
#+AUTHOR: Adam Schwartz
#+DATE: November 11, 2017
#+OPTIONS: ':true *:true toc:nil num:nil

* Setup
The first thing you need to do is download the latest [[https://nginx.org/en/download.html][Nginx source]] into this directory:
#+BEGIN_SRC text
tar vxzf nginx-1.13.6.tar.gz
#+END_SRC

You may also have to install the infamous =pcre= library before compiling Nginx.

Then modify =compile_and_load_modules.sh= and
=add_modules_to_nginx.sh= so that the paths to the Nginx source and
this directory are correct for your machine.

Next, configure and install Nginx to use the two-choices and random modules:
#+BEGIN_SRC text
./add_modules_to_nginx.sh  # may need sudo on the first run
#+END_SRC

By default, Nginx is set to compile without debugging enabled.
However, for development it is recommended to turn debugging on. It's
possible that Nginx will insist on being installed by the superuser, in
which case you will need to either run all scripts in this repository
as root, or grant privilages to =/usr/local/nginx/=.
#+BEGIN_SRC text
./add_modules_to_nginx.sh on
#+END_SRC

You may want to add the =nginx= binary to your path:
#+BEGIN_SRC text
export PATH=/usr/local/nginx/sbin:${PATH}
#+END_SRC

Finally, if any changes are made to the modules, you can recompile with:
#+BEGIN_SRC text
./compile_and_load_modules.sh
#+END_SRC

* Useful Commands
Sometimes, you will need to interact with Nginx directly from the
command line. These are some good things to known:

- start Nginx: =nginx=
- stop Nginx: =nginx -s stop=
- reload =nginx.conf=: =nginx -s reload=
- force quit Nginx: =pkill -f nginx=
